import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Layout from "../components/Layout";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className="appContainer">
      <Layout>
        {/* <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head> */}

        <main className={styles.main}>
          <h1 className={styles.title}>Welcome to Marvelier!</h1>

          <div className={styles.grid}>
            <Link href="/characters">
              <a className={styles.card}>
                <h2>Characters</h2>
                <p>Search Marvel characters and find media recommendations.</p>
              </a>
            </Link>

            <Link href="/comics">
              <a className={styles.card}>
                <h2>Comics</h2>
                <p>
                  Discover comics from Marvel&apos;s vast API - old and new!
                </p>
              </a>
            </Link>

            <Link href="/creators">
              <a className={styles.card}>
                <h2>Creators</h2>
                <p>
                  Explore all of Marvel&apos;s hard-working creators and their
                  work!
                </p>
              </a>
            </Link>

            <Link href="/series">
              <a className={styles.card}>
                <h2>Series</h2>
                <p>
                  Search through Marvel&apos;s long history of putting comics
                  into series.
                </p>
              </a>
            </Link>
          </div>
        </main>
      </Layout>
    </div>
  );
}
